### ISSUE TITLE
zzz_register_dansk_encoding.pth bliver ikke genereret af wheel

### ISSUE THREAD

**Issue by NicolaiSoeborg** [carlbordum/dansk.py#2]
Hvis man `pip install dansk` så bliver `zzz_register_dansk_encoding.pth` ikke genereret (tjek `dansk-0.1.1-py3-none-any.whl` under https://pypi.org/project/dansk/#files)

Hvis man genererer den selv (eller via `python3 setup.py install`) så virker det, men når man så `pip uninstall dansk`, så får man fejl på alt (fordi `zzz_register_dansk_encoding.pth` stadig findes, men ikke kan importe dansk).

**Comment by carlbordum** [comment]
Okay okay,

Koden fandt `site-packages`, når den blev bygget, og ikke under installation. Det betyder at det nok, højst-sandsynligt, i nogle tilfælde ville virke, hvis dit filsystem så ud på en bestemt måde og din bruger hedder `carl`. Jeg anerkender at dette ikke er _helt_ hensynsfuldt og begrænser den potentielle brugerbase unødvendigt.

Der er nye installations instruktioner i læsmig'en.

Pt. bliver `zzz_register_dansk_encoding.pth` stadig efterladt, når man afinstallerer.

Hvis du er interesseret i, hvorfor jeg har valgt den nuværende løsning, så er det pga [den her blog](https://nedbatchelder.com/blog/201001/running_code_at_python_startup.html) og [det her](https://github.com/gvanrossum/pyxl3) repo.

Sig til, hvis det ikke virker og ellers godt nytår!

**Comment by NicolaiSoeborg** [comment]
Ja det er helt perfekt!
